### ISSUE TITLE
DigiDocService i18n errors

### ISSUE THREAD

**Issue by Jyrno42** [thorgate/django-esteid#16]
ERROR_CODES and MID_STATUS_ERROR_CODES attributes for DigiDocService are currently only in Estonian. These errors should be translatable. 

The implementation should allow one to specify the service language via the constructor and it must be possible to change the language in MobileID requests which accept language as input parameter.

Initially we need to add translations for the following languages: Estonian, English, Russian and Lithuanian.

**Comment by ykshatroff** [comment]
This issue seems no longer relevant since DDS has been shut down.
