### ISSUE TITLE
Migrate away from DigiDocService

### ISSUE THREAD

**Issue by Jyrno42** [thorgate/django-esteid#28]
For MID APIs there is a replacement service [Mobile-ID REST API](https://github.com/SK-EID/MID/wiki) which we can start using instead of the DigidocService methods (after #27 is merged since it contains logic to build containers ourselves).

For Smartcard based APIs we consume from dds (PrepareSignature, FinalizeSignature) we can either do everything that is container related ourselves (like we do with smartid in #27) or if there will be a replacement service for smart-card part of dds then we can use that (see https://github.com/SK-EID/dds-documentation/issues/6).

**Comment by ykshatroff** [comment]
I guess we can close this issue now that Authentication is in place 
https://github.com/thorgate/django-esteid/releases/tag/3.1
